### ISSUE TITLE
Map ODKC data to TSC

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastdr#10]
Flesh out https://github.com/dbca-wa/wastdr/blob/master/R/odkc_plan.R
Using {drake} as build tool

* odkc_data updated with latest download_odkc_turtledata_2019
* tsc_data uses new API https://tsc.dbca.wa.gov.au/api/1/encounters-src/ (see https://github.com/dbca-wa/wastd/issues/295)
* make_user_mapping started: extract unique usernames from ODKC, extract TSC user info, see #11 

Do: 

* write function
* write tests
* write man
* use in odkc_as_tsc
* use in split_create_update_skip
* use in upload_odkc_to_tsc

For each of:

- [x] odkc$tracks > turtle-nest-encounters #13 
- [x] odkc$tracks$nest_tag_* > nest-tag-observations
- [x] odkc$tracks_dist > turtle-nest-disturbance-observations
- [x] odkc_data$tracks$egg_count_* > turtle-nest-excavations
- [x] odkc_data$tracks_hatch > turtle-hatchling-morphometrics
- [x] odkc_data$tracks_fan_angle_* > turtle-nest-hatchling-emergences
- [x] odkc_data$tracks_fan_outlier > turtle-nest-hatchling-emergence-outliers
- [x] odkc_data$tracks_light > turtle-nest-hatchling-emergence-light-sources
- [x] odkc_data$tracks_log > logger-encounter
- [x] odkc_data$dist > encounters & turtle-nest-disturbance-observations
- [x] odkc_data$mwi > animal-encounters #16
- [x] odkc_data$mwi > turtle-morphometrics #16 
- [x] odkc_data$mwi_dmg > turtle-damage-observations (needs API) #16
- [x] odkc_data$mwi_tag > tag-observations #16
- [x] odkc_data$tsi > animal-encounters #17 
- [x] odkc_data$track_tally > line-transect-encounters (needs API) #23 
- [x] odkc_data$track_tally > track-tally-observations (needs API) #23
- [x] odkc_data$track_tally > turtle-nest-disturbance-tally-observations #23
- [x] odkc_data$svs / sve > surveys #15 
- [x] all attachments from all tables (all binary fields in form_schema) > media-attachments #19

**Comment by florianm** [comment]
* odkc_data updated with latest download_odkc_turtledata_2019
* tsc_data uses new API https://tsc.dbca.wa.gov.au/api/1/encounters-src/ (see https://github.com/dbca-wa/wastd/issues/295)
* make_user_mapping started: extract unique usernames from ODKC, extract TSC user info
